### ISSUE TITLE
Project Management Tools

### ISSUE THREAD

**Issue by fffej** [red-gate/Tech-Radar#72] opened 2018-11-09 11:51 UTC
We currently used at least:
* JIRA
* GitHub Issues
* Trello

And I've got a feeling there are many more.

I suspect at least @Michael-Upton and @cj-smithy have some opinions here 😄

**Comment by tugberkugurlu** [comment] 2018-11-09 12:35
We as a team have been using GitHub issues for nearly a year now along with [GitHub's project boards](https://help.github.com/articles/about-project-boards/), which have been evolving quite positively and rapidly. It makes the process more efficient for a product team to be able to have issues closer to the environment where we also evolve the codebase. This allows us to take advantage of the tight integration we get between workflows w/o any further effort (e.g. being able to close issues when a PR is merged, more contextual referencing such as [embedded code snippets](https://blog.github.com/2017-08-15-introducing-embedded-code-snippets/)).

Further to this, GitHub is also evolving to be more effective around project management aspects. Latest [Use Related Issues](https://twitter.com/natfriedman/status/1059865385242058752) functionality is a great example to this movement.

On top of this, GitHub has [well-documented, supported APIs](https://developer.github.com/v3/) which would allow us to work around any gaps if we feel an immediate need to do that.

Considering these, I would propose that we take GitHub Issues and Project Boards into Adopt, or at least Explore with clear understanding of what is expected for us to do next to evaluate this further. I would also like us to take JIRA into Endure as I don't see a benefit for us to use JIRA as a separate tool for the job we are already able to get done through GitHub.

There is also the support side to this, where we take the issue from Zendesk to the project management tool when usually the problem is identified. We tried GitHub briefly for SQL Estate Manager with support, @Tianjiaoli might give some insights on how they found GitHub so far from the support side. There were some reservations around how this may work with Zendesk integrations but I believe we identified that integrations should be possible through GitHub APIs (not 100% sure, as I don't know much about Zendesk integrations).

@red-gate/spiders please give your input on how your individual experience have been so far with GitHub as a project management tool compared to alternatives such as JIRA.

**Comment by ChrisHurley** [comment] 2018-11-09 12:45
GitHub's project boards look like a GitHub issue-based version of Trello to me in terms of the way they're organised and how you interact with them. The main thing that I'm missing there (and what JIRA isn't fantastic at either, but we've found a way to kinda do) is creating different swim lanes - we're usually working on one or two larger initiatives which contain many individual tasks, and then have an undercurrent of smaller tasks which don't belong to a larger theme. Is that something you can do with GitHub?

I do think that as we try to move towards more integrated ways of working, using the same technology would be advantageous. The Spiders have, for example, opened some GitHub issues about the Clone/Classification/Mosaic integration on our repo, but we only use JIRA, so we don't look at those (and we weren't clear whose responsibility addressing them would be when we discovered them).

**Comment by adrianbanks** [comment] 2018-11-09 13:00
We use Trello extensively in Hannerheads.

**Comment by nyctef** [comment] 2018-11-09 13:46
The masking team have been using Github exclusively for about a year now, and it's worked reasonably well for us.

We haven't done a lot of support with it, but support have been able to create github issues on our repo (after a bit of confusion about which repo to create issues in) and it looks like support can use the full URL to a github issue as a reference in zendesk (there isn't a nice integration like there is with JIRA, though).

> The main thing that I'm missing there (and what JIRA isn't fantastic at either, but we've found a way to kinda do) is creating different swim lanes - we're usually working on one or two larger initiatives which contain many individual tasks, and then have an undercurrent of smaller tasks which don't belong to a larger theme. Is that something you can do with GitHub?

There's basically two ways you can do this, but neither are great. You can create milestones to group issues in, which lets you track progress on a particular stream of work, but doesn't really integrate with the project board at all. Alternatively, you can just create a second project board :) Most of the time we've been using milestones to track the one thing we're working on, but this sprint we pulled out a second project board for the Clone integration since that was actually independent work.

**Comment by fredjeronimo** [comment] 2018-11-09 17:10
Oh... this is an interesting topic. On Prompt we settled with Jira as it gave an easy entry point to both technical and non-technical users and also because it integrates well with other systems (e.g. Zendesk and Raygun for our support and crash tickets).

**Personal opinion only** - The Prompt team is well aware of my feelings towards Jira, which I believe is _one of the worst project management tools I've ever used in my career_: slow, too much bookkeeping required, hard to keep track of the big picture, requires a lot of discipline to use properly, counter-intuitive workflows, odd design and navigation choices and really questionable decisions (e.g. removal of labels hub in a past version), etc. I suspect that a lot of it derives from the fact that it was not built with that purpose to begin with (when launched in 2002, Jira was purely an issue tracking software, targeted solely at software developers) and the emergent design to follow the industry trends is what lead to its messy current state...

I've used [Hansoft](https://www.perforce.com/products/hansoft) at my previous place and it was a much better experience IMO. A lot of it comes down to how easy it was to switch views and to make changes to the project(s) -- You could pretty much drag and drop everything and have a truly customisable project hierarchy tailored to the needs of the various autonomous teams, which included both technical and non-technical people (and you could have views for short, medium and long term planning all accessible from the same location). From a software engineering perspective, it's nice to be able to consider your project management tool as a true file system:

![image](https://user-images.githubusercontent.com/28531600/48276725-a01b8c80-e440-11e8-9a2c-cc37788f59fc.png)

It's also much faster and the backlog management was a wonderful treat.

**Comment by Michael-Upton** [comment] 2018-11-12 11:30
We don't use any task tracking tools other than a physical whiteboard. We experimented with using Jira's project management features, and although I with my evil project manager hat on quite liked them, the rest  of the team found them too heavyweight.

We *do* use Jira for issue tracking, because we've found it the best way to have a unified view of issues across the multiple projects we're responsible for (SOC and SCA), and with much better bulk update support than GitHub issues. We currently have some GitHub issues in place for the ReadyRoll repo, but we'll be migrating them to Jira.

**Comment by garethbragg** [comment] 2018-11-13 08:49
From the comments so far, I think the _current state_ is:

_Adopt_: Trello
_Adopt_: Jira
_Adopt_: GitHub Issues
_Adopt_: Physical whiteboards

We could even identify _who_ has currently adopted each option, if we felt so inclined.

I don't think this is _great_, but I do think it's where we are. Some thoughts:

* Should we record this on the current Tech-Radar and move on? _If_ this is a problem, the tech radar should be a useful way of highlighting it. We don't need to "solve" is straight away.
* Are there sufficiently different use cases to support such a range of tools? Or should we trend towards a single,default option?
* Would it be worthwhile adding an _Explore_ option for "standardise project management tools", or similar?

**Comment by fffej** [comment] 2018-11-13 15:30
Thanks for the summary @garethbragg .

Let's use this iteration of the radar to summarize the status-quo and we'll work out whether moving towards a single default option is something we want to do (exactly your first option).

**Comment by garethbragg** [comment] 2018-11-19 12:41
I'll PR this.

**Closed** 2018-11-19 13:37 UTC
