### ISSUE TITLE
Tech radar doesn't display in browsers other than Chrome

### ISSUE THREAD

**Issue by smobs** [red-gate/Tech-Radar#94] opened 2018-11-19 08:32 UTC
https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fgithub.com%2Fred-gate%2FTech-Radar%2Fblob%2Fmaster%2Fradar.csv 
 |
 |
v
![image](https://user-images.githubusercontent.com/3480534/48694759-2b311b00-ebd5-11e8-9f42-dbb9b1269107.png)

Following the [FAQ](https://www.thoughtworks.com/radar/how-to-byor), I couldn't see any problems, other eyes might be sharper than mine

**Comment by tugberkugurlu** [comment] 2018-11-19 08:38
Maybe related to this CORS error?
 
![image](https://user-images.githubusercontent.com/328122/48695116-2caf1300-ebd6-11e8-9600-21c5ef5ebced.png)

I believe you need to use the resource from raw.githubusercontent.com, e.g. https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2Fmaster%2Fradar.csv

**Comment by garethbragg** [comment] 2018-11-19 09:01
@tugberkugurlu is right - the radar needs the raw csv to read/render.

**Comment by smobs** [comment] 2018-11-19 09:14
Tugberk's link doesn't render for me either

**Comment by tugberkugurlu** [comment] 2018-11-19 09:17
> Tugberk's link doesn't render for me either

Seems to be working for me. it takes a while to load though if the resource is uncached and you have a slow conn. 

![image](https://user-images.githubusercontent.com/328122/48697145-c7f6b700-ebdb-11e8-853f-d984d3e1aac8.png)

**Comment by garethbragg** [comment] 2018-11-19 09:53
Just checked it in Firefox, and Toby's right - the techradar doesn't render there :( Any ideas, @fffej?

**Comment by adrianbanks** [comment] 2018-11-19 09:58
[Possibly the cause?](https://github.com/thoughtworks/build-your-own-radar/issues/66#issuecomment-428174519)

**Comment by tugberkugurlu** [comment] 2018-11-19 10:51
> Possibly the cause?

seems like that's it:

![image](https://user-images.githubusercontent.com/328122/48702551-1c546380-ebe9-11e8-9da0-1f835943769a.png)

**Comment by fffej** [comment] 2018-11-19 13:37
I'm going to close this issue because it's not something we can resolve (unless anyone wants to make a PR downstream!).

**Closed by fffej** 2018-11-19 13:37 UTC
